
inherit_settings: True

# assume enough RAM to not chunk
chunk_training_mode: disabled

# input tables
input_table_list:
  # accessibility
  - tablename: accessibility
    filename: accessibility.csv
    index_col: zone_id
    keep_columns:
      - auPkRetail
      - auPkTotal
      - auOpRetail
      - auOpTotal
      - trPkRetail
      - trPkTotal
      - trOpRetail
      - trOpTotal
      - nmRetail
      - nmTotal
      - TotalAcc
  #
  # households (table index 'household_id')
  #
  - tablename: households
    filename: survey_data/override_households.csv
    index_col: household_id
    keep_columns:
      - home_zone_id
      - income
      - hhsize
      - HHT
      - auto_ownership
      - num_workers
      - hh_race_category
      - hh_weight
      - household_id_original
  
  #
  # persons (table index 'person_id')
  #
  - tablename: persons
    filename: survey_data/override_persons.csv
    index_col: person_id
    keep_columns:
      - household_id
      - age
      - PNUM
      - sex
      - pemploy
      - pstudent
      - ptype
      - household_id_original
      - person_id_elmer_original
      - person_weight
  #
  # land_use (table index 'zone_id')
  #
  - tablename: land_use
    filename: land_use.csv
    index_col: zone_id
    rename_columns:
      MAZ: zone_id
      COUNTY: county_id
    keep_columns:
      - TAZ
      - DISTRICT
      - SD
      - county_id
      - TOTHH
      - TOTPOP
      - TOTACRE
      - RESACRE
      - CIACRE
      - TOTEMP
      - AGE0519
      - RETEMPN
      - FPSEMPN
      - HEREMPN
      - OTHEMPN
      - AGREMPN
      - MWTEMPN
      - FOOEMPN
      - PRKCST
      - OPRKCST
      - area_type
      - HSENROLL
      - COLLFTE
      - COLLPTE
      - TOPOLOGY
      - TERMINAL
      - transit_score_scaled
#      - density_index
      - buff_density_index
      - GSENROLL
      - access_dist_transit
      - hh_1
      - emptot_1

write_raw_tables: False
rng_base_seed: 0

use_shadow_pricing: False

# turn writing of sample_tables on and off for all models
# (if True, tables will be written if DEST_CHOICE_SAMPLE_TABLE_NAME is specified in individual model settings)
want_dest_choice_sample_tables: False

# number of households to simulate
households_sample_size:  0

# to resume after last successful checkpoint, specify resume_after: _
resume_after: free_parking

#trace_hh_id: 3404

output_tables:
  h5_store: False
  action: include
  prefix: final_
  sort: True
  tables:
    - checkpoints
    - accessibility
    - land_use
    - households
    - persons

models:
  - initialize_proto_population # Separate step so proto tables can be split for multiprocess.
  - compute_disaggregate_accessibility
  - initialize_landuse
#  - compute_accessibility
  - initialize_households
  - auto_ownership_simulate
  - school_location
  - work_from_home
  - workplace_location
  - free_parking
  - telecommute_frequency
  - cdap_simulate
  - mandatory_tour_frequency
  - mandatory_tour_scheduling
  - joint_tour_frequency
  - joint_tour_composition
  - joint_tour_participation
  - joint_tour_destination
  - joint_tour_scheduling
  - non_mandatory_tour_frequency
  - non_mandatory_tour_destination
  - non_mandatory_tour_scheduling
  - tour_mode_choice_simulate
  - atwork_subtour_frequency
  - atwork_subtour_destination
  - atwork_subtour_scheduling
  - atwork_subtour_mode_choice
  - stop_frequency
  - trip_purpose
  - trip_destination
  - trip_purpose_and_destination
  - trip_scheduling
  - trip_mode_choice
  - write_data_dictionary
  - track_skim_usage
#  - write_trip_matrices
  - write_tables

