inherit_settings: True

MKL_NUM_THREADS: 1
#activitysim run -c configs_mp -s settings_mp.yaml -c configs -d data/full -o output_test

# turn shadow_pricing on and off for all models (e.g. school and work)
# shadow pricing is deprecated for less than full samples
# see shadow_pricing.yaml for additional settings
use_shadow_pricing: False
#chunk_size: 115_000_000_000
chunk_training_mode: disabled
#chunk_method: uss

# raise error if any sub-process fails without waiting for others to complete
fail_fast: True

multiprocess: True
num_processes: 2

multiprocess_steps:
  - name: mp_initialize
    begin: initialize_landuse
  - name: mp_accessibility
    begin: compute_accessibility
    slice:
      tables:
        - accessibility
      exclude: True
  - name: mp_initialize_hh
    begin: initialize_households
  - name: mp_households
    begin: school_location
    slice:
      tables:
        - households
        - persons
  - name: mp_summarize
    begin: write_data_dictionary

output_tables:
  h5_store: False
  action: include
  prefix: final_
  sort: True
  tables:
    - checkpoints
    - accessibility
    - land_use
    - households
    - persons
 

