---
title: "size-term-estimation"
author: "suzanne"
date: "2023-04-13"
output: html_document
---

# Read in libraries, set working directory, source code for doing the size estimation work
```{r}
library(dplyr)
library(tidyverse)
# for mapping places that have people going to them, but size variables are zero:
library(sf)
library(leaflet)
library(htmlwidgets)
library(stats)
library(data.table)

#put your input data here, outputs will also be written out here
setwd("R:/activitysim/estimation/2017_2019_data/size_terms")

#this file does the work
source('size_estimation_dest_choice.R')

```


This is your input file that includes for each zone, number of trips by purpose and the size variables.
```{r}

trips_purp_lu<-read.csv('size_terms_2017_2019.csv')
trips_purp_lu<-trips_purp_lu%>%mutate(logaparks=log(1+aparks))

```



write out the list of columns that could be used in the estimation
```{r}

var_list<-c('empedu_p',	'empfoo_p', 'empgov_p',	'empind_p',	'empmed_p',	'empofc_p',	'empoth_p',	'empret_p',	'emprsc_p',	'empsvc_p',	'emptot_p',	'hh_p',	'stugrd_p',	'stuhgh_p',	'stuuni_p',	'logaparks')
all_lu_vars<-data.frame(Variable=var_list,Zeros=rep(0,(length(var_list))))
 

```



```{r}
trips_purp_lu_meal<- trips_purp_lu%>%select(zone, eatout, empfoo_p, empret_p, empsvc_p, empofc_p)
coeff_small<-estimate_size_terms(trips_purp_lu_meal, 'outputs/eatout_size.csv', all_lu_vars)

```


```{r}
trips_purp_lu_escort<- trips_purp_lu%>%select(zone, escort, empsvc_p,empedu_p,  empgov_p, empret_p, empmed_p,  hh_p, stugrd_p, stuhgh_p)
estimate_size_terms(trips_purp_lu_escort, 'outputs/escort_size.csv',all_lu_vars)

```



```{r}
trips_purp_lu_other_discr<- trips_purp_lu%>%select(zone, othdiscr, empsvc_p,empedu_p,empfoo_p,empret_p,hh_p, logaparks)
estimate_size_terms(trips_purp_lu_other_discr, 'outputs/other_discr_size.csv', all_lu_vars)
```

```{r}
trips_purp_lu_highschool<- trips_purp_lu%>%select(zone,highschool,stuhgh_p,  empedu_p)
estimate_size_terms(trips_purp_lu_highschool, 'outputs/highschool_size.csv', all_lu_vars)

```

```{r}
trips_purp_lu_uni<- trips_purp_lu%>%select(zone,univ,stuuni_p,  empedu_p)
estimate_size_terms(trips_purp_lu_uni, 'outputs/univeristy_size.csv', all_lu_vars)

```

```{r}
trips_purp_lu_shopping<- trips_purp_lu%>%select(zone, shopping, empret_p, empfoo_p, empoth_p, empsvc_p, hh_p)
estimate_size_terms(trips_purp_lu_shopping, 'outputs/shopping_size.csv', all_lu_vars)

```
```{r}
trips_purp_lu_social<- trips_purp_lu%>%select(zone, social, empsvc_p,hh_p, empfoo_p, empsvc_p, empret_p, empoth_p, logaparks)
estimate_size_terms(trips_purp_lu_social, 'outputs/social_size.csv', all_lu_vars)

```
```{r}
trips_purp_lu_work_high<- trips_purp_lu%>%select(zone, work_high, empofc_p,empsvc_p, empedu_p, empfoo_p, empind_p, empmed_p,  empoth_p)
estimate_size_terms(trips_purp_lu_work_high, 'outputs/work_high.csv', all_lu_vars)

```
```{r}
trips_purp_lu_work_very_high<- trips_purp_lu%>%select(zone, work_very_high, empofc_p, empsvc_p, empedu_p, empfoo_p, empind_p, empmed_p)
estimate_size_terms(trips_purp_lu_work_very_high, 'outputs/work_very_high.csv', all_lu_vars)
```
```{r}
trips_purp_lu_work_med<- trips_purp_lu%>%select(zone, work_med, empsvc_p, empfoo_p, empofc_p, empoth_p, empret_p, empind_p, empmed_p,  empoth_p,empedu_p)
estimate_size_terms(trips_purp_lu_work_med, 'outputs/work_med.csv', all_lu_vars)
```
```{r}
trips_purp_lu_work_low<- trips_purp_lu%>%select(zone, work_low, empsvc_p, empfoo_p, empofc_p, empoth_p, empret_p, empind_p, empmed_p,  empoth_p,empedu_p,logaparks)
estimate_size_terms(trips_purp_lu_work_low, 'outputs/worklow.csv', all_lu_vars)
```
