#inherit_settings: True
#sharrow: require

# activitysim run -c configs -d data -o output


# number of households to simulate
#households_sample_size:  100
# simulate all households
households_sample_size: 0

#chunk_size: 
#chunk_size: 123_000_000_000
#chunk_training_mode: production
# set false to disable variability check in simple_simulate and interaction_simulate
check_for_variability: False

# - shadow pricing global switches

# turn shadow_pricing on and off for all models (e.g. school and work)
# shadow pricing is deprecated for less than full samples
# see shadow_pricing.yaml for additional settings
use_shadow_pricing: False

# turn writing of sample_tables on and off for all models
# (if True, tables will be written if DEST_CHOICE_SAMPLE_TABLE_NAME is specified in individual model settings)
want_dest_choice_sample_tables: False

# - tracing

# trace household id; comment out or leave empty for no trace
# households with all tour types
trace_hh_id: 11219


# trace origin, destination in accessibility calculation; comment out or leave empty for no trace
#trace_od:


# input tables
input_table_list:
  - tablename: households
    filename: households.csv
    index_col: household_id
    rename_columns:
      HHID: household_id
      PERSONS: hhsize
      workers: num_workers
      VEHICL: auto_ownership
      MAZ: home_zone_id
    recode_columns:
      home_zone_id: land_use.zone_id
    keep_columns:
      - home_zone_id
      - income
      - hhsize
      - HHT
      - auto_ownership
      - num_workers
  - tablename: persons
    filename: persons.csv
    index_col: person_id
    rename_columns:
      PERID: person_id
    keep_columns:
      - household_id
      - age
      - PNUM
      - sex
      - pemploy
      - pstudent
      - ptype
  - tablename: land_use
    filename: land_use.csv
    index_col: zone_id
    rename_columns:
      MAZ: zone_id
      COUNTY: county_id
    recode_columns:
      zone_id: zero-based
      TAZ: land_use_taz.TAZ
    keep_columns:
      - TAZ
      - DISTRICT
      - SD
      - county_id
      - TOTHH
      - TOTPOP
      - TOTACRE
      - RESACRE
      - CIACRE
      - TOTEMP
      - AGE0519
      - RETEMPN
      - FPSEMPN
      - HEREMPN
      - OTHEMPN
      - AGREMPN
      - MWTEMPN
      - PRKCST
      - OPRKCST
      - area_type
      - HSENROLL
      - COLLFTE
      - COLLPTE
      - TOPOLOGY
      - TERMINAL
      - transit_score_scaled
#      - density_index
      - buff_density_index
      - GSENROLL
      - access_dist_transit
      - hh_1
      - emptot_1
  - tablename: land_use_taz
    filename: taz.csv
    index_col: TAZ
    recode_columns:
      TAZ: zero-based
# to resume after last successful checkpoint, specify resume_after: _
#resume_after: compute_accessibility

models:
  ## Disaggregate Accessibility steps
  - initialize_proto_population # Separate step so proto tables can be split for multiprocess.
  - compute_disaggregate_accessibility
  - initialize_landuse
  - compute_accessibility
  - initialize_households
  - auto_ownership_simulate
  - school_location
  - work_from_home
  - workplace_location
  - free_parking
  - telecommute_frequency
  - cdap_simulate
  - mandatory_tour_frequency
  - mandatory_tour_scheduling
  - joint_tour_frequency
  - joint_tour_composition
  - joint_tour_participation
  - joint_tour_destination
  - joint_tour_scheduling
  - non_mandatory_tour_frequency
  - non_mandatory_tour_destination
  - non_mandatory_tour_scheduling
  - tour_mode_choice_simulate
  - atwork_subtour_frequency
  - atwork_subtour_destination
  - atwork_subtour_scheduling
  - atwork_subtour_mode_choice
  - stop_frequency
# - trip_purpose
# - trip_destination
# - trip_purpose_and_destination
# - trip_scheduling
# - trip_mode_choice
  - write_data_dictionary
#  - track_skim_usage
#  - write_trip_matrices
  - write_tables


output_tables:
  h5_store: False
  action: include
  prefix: final_
  sort: True
  tables:
    - checkpoints
    - accessibility
    - tablename: land_use
      decode_columns:
        zone_id: land_use.zone_id
    - tablename: households
      decode_columns:
        home_zone_id: land_use.zone_id
    - tablename: persons
      decode_columns:
        home_zone_id: land_use.zone_id
        school_zone_id: nonnegative | land_use.zone_id
        workplace_zone_id: nonnegative | land_use.zone_id
    - tablename: tours
      decode_columns:
        origin: land_use.zone_id
        destination: land_use.zone_id
    - tablename: trips
      decode_columns:
        origin: land_use.zone_id
        destination: land_use.zone_id
    - joint_tour_participants
    - proto_disaggregate_accessibility

# area_types less than this are considered urban
urban_threshold: 4
cbd_threshold: 2
rural_threshold: 6
